# $Id$

miunasgn.pdf: miunasgn.tex literature.tex examination.tex literature.bib
miunasgn.pdf: miunmisc

INCLUDE_MIUNTEX=../
INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/tex.mk
include ${INCLUDE_MAKEFILES}/miun.depend.mk

clean-miunasgn:
	true # don't clean these files
