# $Id$

miunprot.pdf: miunprot.tex miunmisc

INCLUDE_MIUNTEX=../
INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/tex.mk
include ${INCLUDE_MAKEFILES}/miun.depend.mk

clean-miunprot:
	true # don't clean these files
