# $Id$

miunexam.pdf: miunexam.tex

INCLUDE_MIUNTEX=../
INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/tex.mk
include ${INCLUDE_MAKEFILES}/miun.depend.mk

clean-miunexam:
	true # don't clean these files
