# $Id$

miunart.pdf: miunart.tex miunart.bib automata.eps miunmisc

INCLUDE_MIUNTEX=../
INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/tex.mk
include ${INCLUDE_MAKEFILES}/miun.depend.mk

clean-miunart:
	true # don't clean these files

